jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Maven Compile
      run: mvn -X compile -B --file pom.xml
    - continue-on-error: true
      name: Maven Verify
      run: mvn -X verify -B --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 17
        - 21
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
