jobs:
  Fuzzing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: build
      name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        dry-run: false
        language: jvm
        oss-fuzz-project-name: jsoup
    - continue-on-error: true
      name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        dry-run: false
        fuzz-seconds: 600
        language: jvm
        oss-fuzz-project-name: jsoup
    - continue-on-error: true
      if: failure() && steps.build.outcome == 'success'
      name: Upload Crash
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./out/artifacts
name: CIFuzz
on:
  repository_dispatch:
    types: trigger-ga___cifuzz.yml
